# Generated by Django 5.0.1 on 2024-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master_report2',
        ),
        migrations.AddField(
            model_name='manufactory_report',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='master_report',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
